name: Build & Deploy to Pages

# https://qiita.com/nwtgck/items/e9a355c2ccb03d8e8eb0

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: volta-cli/action@v1

    - run: npm install
    - run: npm build

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs